# Target architecture of the UML kernel binary file. Valid values include:
# i386, ia64, ppc, and x86_64
SUBARCH?=x86_64

# Kernel release
KERNEL_RELEASE?=4.5.1

# URL of the kernel tarball, if required
KERNEL_SUFFIX=.tar.xz
# Nassty kernel.org redirects to https (which is bad for caching)
#KERNEL_URL=http://www.kernel.org/pub/linux/kernel/v3.x/linux-$(KERNEL_RELEASE)$(KERNEL_SUFFIX)
KERNEL_URL=http://ftp.funet.fi/pub/linux/kernel/v4.x/linux-$(KERNEL_RELEASE)$(KERNEL_SUFFIX)
